namespace Expresso.Parsing.Test.Policies;

// Literal query corpus captured from the existing parser tests. Generated from
// their C# string tokens; dynamic function families are covered by the catalog sweep.
internal static partial class PolicyParserCorpus
{
    internal static IEnumerable<object[]> Part0()
    {
        yield return new object[] { @"any(authors, eq(displayname, ""Leo Tolstoy""))", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"eq(count(authors), 2)", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"any(authors)", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"any(authors, any(awards, eq(name, ""Nobel Prize"")))", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"gt(min(authors, dateofbirth), ""1828-01-01"")", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"eq(min(price, rating), rating)", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"eq(displayname, ""Leo Tolstoy"")", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"any(tags)", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"eq(sum(price, rating), 1)", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"all(authors)", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"count(authors),desc", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"any(authors),asc", false, @"dateofbirth:DateTime;displayname:string;firstname:string;name:string;price:double;rating:double;score:int;title:string;year:int" };
        yield return new object[] { @"eq(dateFrom, ""2020-01-15"")", false, @"dateFrom:DateTime" };
        yield return new object[] { @"eq(id, ""{SampleGuid}"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"in(id, ""{SampleGuid}"", ""{Guid.Empty}"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"isnull(id)", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"gt(id, ""{SampleGuid}"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(dateFrom, ""1899-12-31"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(opens, ""14:30"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(opens, ""14:30:45"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(opens, ""25:00"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(opens, ""1.14:30"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(time(dateFrom), ""14:30"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(born, ""2020-01-15"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"gt(adddays(born, 1), born)", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(date(dateFrom), dateFrom)", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(time(dateFrom), ""14:30:00"")", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(addhours(born, 1), born)", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"eq(adddays(starts, 1), starts)", false, @"born:DateOnly;dateFrom:DateTime;id:Guid;opens:TimeSpan;starts:TimeOnly" };
        yield return new object[] { @"and(eq(name, ""John""), gt(age, 25))", false, @"" };
        yield return new object[] { @"or(eq(name, ""John""), gt(age, 25))", false, @"" };
        yield return new object[] { @"not(eq(name, ""John""))", false, @"" };
        yield return new object[] { @"eq(name, ""John"")", false, @"" };
        yield return new object[] { @"neq(name, ""John"")", false, @"" };
        yield return new object[] { @"gt(age, 25)", false, @"" };
        yield return new object[] { @"gte(age, 25)", false, @"" };
        yield return new object[] { @"lt(age, 30)", false, @"" };
        yield return new object[] { @"lte(age, 30)", false, @"" };
        yield return new object[] { @"in(name, ""John"", ""Jane"")", false, @"" };
        yield return new object[] { @"startswith(name, ""Jo"")", false, @"" };
        yield return new object[] { @"eq(abs(age),1)", false, @"" };
        yield return new object[] { @"eq(add(age,1),1)", false, @"" };
        yield return new object[] { @"eq(sub(age,1),1)", false, @"" };
        yield return new object[] { @"eq(mult(age,1),1)", false, @"" };
        yield return new object[] { @"eq(div(age,1),1)", false, @"" };
        yield return new object[] { @"and(or(startswith(name,""Jo""),in(substring(name,1,3),""Mary"",""Susan"")),gt(age,25),lt(dateFrom,dateTo),not(eq(""Some Foo"", foo)))", false, @"" };
        yield return new object[] { @"and(.eq(name, ""John""), gt(age, 25))", false, @"" };
        yield return new object[] { @"invalid(name, ""John"")", false, @"" };
        yield return new object[] { @"eq(invalidField, ""John"")", false, @"" };
        yield return new object[] { @"eq(name, 123)", false, @"" };
        yield return new object[] { @"gt(doubleField, 3.14)", false, @"" };
        yield return new object[] { @"AND(eq(name, ""John""), gt(age, 25))", false, @"" };
        yield return new object[] { @"eq(NAME, ""John"")", false, @"" };
        yield return new object[] { @"eq(file_name, ""do.exe"")", false, @"" };
        yield return new object[] { @"and()", false, @"" };
        yield return new object[] { @"And() function should at least 2 arguments", false, @"" };
        yield return new object[] { @"eq(substring(name, 1), ""J"")", false, @"" };
        yield return new object[] { @"Substring() function should have 3 arguments", false, @"" };
        yield return new object[] { @"eq(substring(name, 1, 1, 1), ""J"")", false, @"" };
        yield return new object[] { @"eq((name, ""John"")", false, @"" };
        yield return new object[] { @"and(eq(name, ""John""),)", false, @"" };
        yield return new object[] { @"eq(name, ""John""))", false, @"" };
        yield return new object[] { @"eq(name,", false, @"" };
        yield return new object[] { @"eq(,name, ""John"")", false, @"" };
        yield return new object[] { @"isnull(name)", false, @"" };
        yield return new object[] { @"and(isnull(name), gt(age, 25))", false, @"" };
        yield return new object[] { @"isnull(name, age)", false, @"" };
        yield return new object[] { @"eq(status, 5)", false, @"" };
        yield return new object[] { @"gt(status, 10)", false, @"" };
        yield return new object[] { @"eq(add(status, 5), 15)", false, @"" };
        yield return new object[] { @"eq(abs(status), 5)", false, @"" };
        yield return new object[] { @"in(status, 1, 2, 3)", false, @"" };
        yield return new object[] { @"isnull(status)", false, @"" };
        yield return new object[] { @"and(gt(status, 5), lt(age, 30))", false, @"" };
        yield return new object[] { @"eq(year(dateFrom), 2020)", false, @"" };
        yield return new object[] { @"eq(month(dateFrom), 1)", false, @"" };
        yield return new object[] { @"eq(day(dateFrom), 15)", false, @"" };
        yield return new object[] { @"eq(dayofyear(dateFrom), 32)", false, @"" };
        yield return new object[] { @"eq(hour(dateFrom), 12)", false, @"" };
        yield return new object[] { @"eq(minute(dateFrom), 30)", false, @"" };
        yield return new object[] { @"eq(second(dateFrom), 0)", false, @"" };
        yield return new object[] { @"eq(dayofweek(dateFrom), 0)", false, @"" };
        yield return new object[] { @"eq(date(dateFrom), ""2020-01-01"")", false, @"" };
        yield return new object[] { @"eq(date(dateFrom), dateTo)", false, @"" };
        yield return new object[] { @"eq(year(""2020-01-15""), 2020)", false, @"" };
        yield return new object[] { @"gt(addyears(dateFrom, 1), dateTo)", false, @"" };
        yield return new object[] { @"gt(addmonths(dateFrom, 0), dateTo)", false, @"" };
        yield return new object[] { @"gt(adddays(dateFrom, -7), dateTo)", false, @"" };
        yield return new object[] { @"gt(addhours(dateFrom, 24), dateTo)", false, @"" };
        yield return new object[] { @"gt(addminutes(dateFrom, -30), dateTo)", false, @"" };
        yield return new object[] { @"gt(addseconds(dateFrom, 0), dateTo)", false, @"" };
        yield return new object[] { @"eq(year(adddays(dateFrom, 1)), 2020)", false, @"" };
        yield return new object[] { @"eq(adddays(name, 1), dateTo)", false, @"" };
        yield return new object[] { @"gt(adddays(dateFrom, 1.5), dateTo)", false, @"" };
        yield return new object[] { @"eq(year(age), 2020)", false, @"" };
        yield return new object[] { @"eq(year(), 2020)", false, @"" };
        yield return new object[] { @"eq(year(dateFrom, dateTo), 2020)", false, @"" };
        yield return new object[] { @"Year() function should have 1 argument", false, @"" };
        yield return new object[] { @"gt(adddays(dateFrom), dateTo)", false, @"" };
        yield return new object[] { @"Adddays() function should have 2 arguments", false, @"" };
    }
}
