<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <PackageId>Expresso.Rendering.SqlServer</PackageId>
    <Title>Expresso.Rendering.SqlServer</Title>
    <Description>Render Expresso expression trees to parameterized SQL Server WHERE and ORDER BY clauses.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.1" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" Condition="'$(TargetFramework)' == 'net6.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Expresso.Core\Expresso.Core.csproj" />
  </ItemGroup>

</Project>
