using Expresso.Core.CriteriaExpressions;

namespace Expresso.Parsing.Policies.Runtime;

internal sealed partial class PolicyEvaluator
{
    public NodeFacts VisitField(Field node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitLiteral(Literal node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitCollectionRef(CollectionRef node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAnd(AndFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitOr(OrFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitNot(NotFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitEq(EqFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitNeq(NeqFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitGt(GtFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitGte(GteFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitLt(LtFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitLte(LteFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitIn(InFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitIsNull(IsNullFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAbs(AbsFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAdd(AddFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitSub(SubFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitMult(MultFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitDiv(DivFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitMod(ModFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitFloor(FloorFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitCeiling(CeilingFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitRound(RoundFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitSign(SignFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitPower(PowerFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitSqrt(SqrtFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitMin(MinFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitMax(MaxFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAny(AnyFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAll(AllFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitNone(NoneFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitCollectionCount(CollectionCountFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitCollectionMin(CollectionMinFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitCollectionMax(CollectionMaxFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitCollectionSum(CollectionSumFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitCollectionAvg(CollectionAvgFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitStrStartswith(StrStartswithFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitStrEndswith(StrEndswithFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitStrContains(StrContainsFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitSubString(SubStringFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitLeft(LeftFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitRight(RightFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitConcat(ConcatFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitLower(LowerFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitUpper(UpperFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitTrim(TrimFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitLTrim(LTrimFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitRTrim(RTrimFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitReplace(ReplaceFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitLen(LenFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitIndexOf(IndexOfFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitYear(YearFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitMonth(MonthFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitDay(DayFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitDayOfYear(DayOfYearFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitHour(HourFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitMinute(MinuteFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitSecond(SecondFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitDayOfWeek(DayOfWeekFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitDate(DateFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitTime(TimeFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAddYears(AddYearsFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAddMonths(AddMonthsFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAddDays(AddDaysFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAddHours(AddHoursFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAddMinutes(AddMinutesFunc node, EvalContext context) => Evaluate(node, context);
    public NodeFacts VisitAddSeconds(AddSecondsFunc node, EvalContext context) => Evaluate(node, context);
}
